version: '3'

services:
  factom-api:
    build: .
    volumes:
      - .:/src
    extra_hosts:
      - localhost:172.17.0.1
  factom-sandbox:
    image: bhomnick/factom
    ports:
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
    volumes:
      - factomdata:/root/.factom/
    extra_hosts:
      - localhost:172.17.0.1

volumes:
  factomdata:
