version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            pyenv local 3.7.0
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Lint code
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Install python test versions
          command: |
            git clone git://github.com/pyenv/pyenv-update.git $(pyenv root)/plugins/pyenv-update
            pyenv update
            pyenv install 3.8.5
            pyenv local 3.5.2 3.6.5 3.7.0 3.8.5
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox
